### ISSUE TITLE
Activate P3 pin

### ISSUE THREAD

**Issue by haithembelhaj** [calliope-edu/scratch-gui#2]
The device should react to P3 events

**Comment by joernalraun** [comment]
@Amerlander

**Comment by haithembelhaj** [comment]
@joernalraun @Amerlander For the pin 3 to work we need to make sure the modified scratch-vm matches the hex service code

I guessed I need to change the following code
https://github.com/calliope-edu/scratch-vm/commit/86d3889fdf4d679af34f1522620c2e8f76ccd0a4
I think most importantly the MbitMoreButtonID must match the exposed mbitmore service button id in the hex

@Amerlander I saw you made some changes to the pxt-scratch-more here https://github.com/calliope-edu/pxt-Scratch-more/tree/add-p3

Was that successful? Can I have the Hex for that version if so? 

@Amerlander I really think we should make a small session together to get the p3 working on both sides. Do you have some time for a pairing session the next work days? Maybe on monday?

**Comment by Amerlander** [comment]
Actually I'm not sure if it was successfull, since I could not test it in scratch.
Also the P0-2 events were not working as expected anymore, but as I havent tested that before the changes I'm not sure if that is new.

Here is the hex:
[add-p3.zip](https://github.com/calliope-edu/scratch-gui/files/15022868/add-p3.zip)
